### ISSUE TITLE
How to setup with cron and crontab file

### ISSUE THREAD

**Issue by user0210** [VibroAxe/wsl_automount#1]
Hello, Im new here and I hope I´m doing this the propper way…
For now I tried to put
@reboot /path to file/wsl_automount.ps1
in the crontab file, and then install the wsl_automount.sh with no luck….

do you know how to set it up?

**Comment by VibroAxe** [comment]
Hi @philor1 I'm not sure what you are trying to do with crontab, the ps1 script needs to be in WINDOWS scheduled tasks as it's a powershell script which uses the windows event bus to watch for drive attachment

(See step 2 in the README)

**Comment by VibroAxe** [comment]
@philor1 any joy? I'm going to close this issue in a week if you don't respond
